name: pushfire_sdk
description: A lightweight push notification tracking SDK for Firebase.
homepage: https://github.com/FlywheelStudio/pushfire_sdk/blob/main/README.md
repository: https://github.com/FlywheelStudio/pushfire_sdk

version: 0.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  http: ^1.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# This section should be outside of `dev_dependencies`
example:
  path: example

flutter:
  # Add your assets or fonts here if needed in the future
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
